= Búraló Technologies Identifier

== Overview

Generate domain object identifiers from UUIDs that are globally unique and sortable in their binary and textual representation.

== Java Compatibility

This library was created using Java 21.

== Getting Started without Spring Boot

* Add the following dependency to your *pom.xml*:
+
[source,xml]
----
<dependency>
    <groupId>com.buralotech.oss.identifier</groupId>
    <artifactId>buralotech-identifier-core</artifactId>
    <version>1.4.1</version>
</dependency>
----

* Instantiate `UUIDIdentifierService` which implements the `IdenterifierService` and provide it with the delegate corresponding to the UUID format you wish to use:
+
[source,java]
----
private final IdentifierService identifierService = new UUIDIdentifierService(new UUIDVersion6Delegate());
----

The following delegates are available:

* `UUIDVersion6Delegate` (recommended)-- uses the standard Type 6 UUID format which was designed with database locality in mind.

* `UUIDVersion1Delegate` (deprecated) -- uses a modified/non-standard Type 1 UUID format to improve database locality.

== Spring Boot Usage

* Add the following dependencies to your *pom.xml*:
+
[source,xml]
----
<dependency>
    <groupId>com.buralotech.oss.identifier</groupId>
    <artifactId>buralotech-identifier-core</artifactId>
    <version>1.4.1</version>
</dependency>
----
+
[source,xml]
----
<dependency>
    <groupId>com.buralotech.oss.identifier</groupId>
    <artifactId>buralotech-identifier-spring</artifactId>
    <version>1.4.0</version>
</dependency>
----

* The `buralotech-identifier-spring` contains autoconfiguration that exports an `IdentifierService` and `IdentifierConverter` bean. The `IdentifierConverter` bean allows conversion from the string representation.

* Auto-wire the `IdentifierService` bean:
+
[source,java]
----
@Autowired
private IdentifierService identifierService;
----

* Type 7 UUIDs are used by default. If you want to use the now deprecated modified Type 1 UUIDs then you will need to override the following property:
+
----
buralotech.identifier.generator=v1
----

* Type 6 UUIDs are also supported and can be used by setting the same property as follows:
+
----
buralotech.identifier.generator=v6
----

== Generating identifiers

* Generate an identifier:
+
[source,java]
----
var id = identifierService.generate();
----

* `id` is a record of type `UUIDIdentifier` which implements the `Identifier` interface.

* `id.binary()` returns a `byte[16]` array that con be stored in a `BINARY(16)` column in the database.
+
[source,java]
----
PreparedStatement ps = /* ... */;
ps.setBytes(1, id.binary());
----

* `id.text()` returns a 22 character URL-safe string that can be used in RESTful APIs as part of the URI path or in request/response payloads.

== Parsing binary and text representations

* If you read `byte[16]` from a `BINARY(16)` database column use the `identifierService.fromBinary(bytes
[])` method to convert it to an `Identifier`:
+
[source,java]
----
ResultSet rs = /* ... */;
var bytes = rs.getBytes(1);
var id = identifierService.fromBinary(bytes);
----

* To convert a `String` passed via request URI or payload you can use the `identifierService.fromText(String)` method.

== Working with timestamps

* Type 1, Type 6 and Type 6 UUIDs contain the timestamp of the generation time. This means the identifier can do double duty since it is both the unique identifier and the creation date/time.

* You can extract the timestamp from the identifier using `IdentifierService.toInstant(Identifier)`.

* If you want to search for entities created with a certain time window you can us `IdentifierService.asLowerBound(Temporal)` and `IdentifierService.asUpperBound(Temporal)` to get identifiers to use in the range query.

== License & Source Code

The **Búraló Technologies Identifier** is made available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License] and the source code is hosted on http://github.com[GitHub] at https://github.com/BuraloOSS/buralo-identiifer.
